# Generated by Django 2.1.4 on 2019-08-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190823_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAriticlesType',
            new_name='BlogArticlesType',
        ),
    ]
